export const LOGO_URL = "https://customer-assets.emergentagent.com/job_fancy-upgrade/artifacts/iserhwlr_Untitled%20design-2.png";

export const BRAND = {
  name: "BLACKROCK",
  tagline: "Restaurant & Lounge",
  phone: "+234 903 048 2774",
  phoneTel: "+2349030482774",
  email: "info@blackrockrestaurantng.com",
  whatsapp: "https://wa.me/2348055238353?text=Hello%20BLACKROCK%2C%20I%27d%20like%20to%20enquire%20about%20a%20reservation.",
  address: "11 Ajao Road, off Adeniyi Jones Road, Ikeja, Lagos",
  hours: [
    { day: "Daily", time: "10:00 AM — 11:59 PM" },
  ],
};

export const NAV_LINKS = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Menu", to: "/menu" },
  { label: "Gallery", to: "/gallery" },
  { label: "Contact", to: "/contact" },
];

export const OCCASIONS = [
  { id: "date-night", label: "Date Night", note: "An intimate table for two. Let us help you set the mood.", concierge: false },
  { id: "birthday", label: "Birthday Celebration", note: "A meal they'll remember. Cake, candles, full attention.", concierge: false },
  { id: "family", label: "Family Gathering", note: "Bring everyone together over a table that feels like home.", concierge: false },
  { id: "corporate", label: "Corporate Dining", note: "Refined hosting for clients, partners and teams — lunch or dinner.", concierge: false },
  { id: "anniversary", label: "Anniversary", note: "Mark the years with something quietly extraordinary.", concierge: false },
  { id: "proposal", label: "Proposal", note: "This one deserves a personal touch. Let us help you plan it.", concierge: true },
  { id: "private-dining", label: "Private Dining", note: "Our private dining experience is fully tailored to your group.", concierge: true },
  { id: "special", label: "Special Occasion", note: "Tell us what you're celebrating. We'll take care of the rest.", concierge: false },
];

// Curated imagery - Nigerian / Lagos / West African
// Hero: very dark image so text reads. Other images mix Nigerian food + warm lounge.
export const IMAGES = {
  heroRooftop: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2400&auto=format&fit=crop",
  heroAlt: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2400&auto=format&fit=crop",
  loungeDark: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?q=80&w=2000&auto=format&fit=crop",
  rooftopNight: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2000&auto=format&fit=crop",
  rooftopDay: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2000&auto=format&fit=crop",
  bar: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=2000&auto=format&fit=crop",
  cocktail: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1600&auto=format&fit=crop",
  // Food & drink - local uploads
  jollof: "/809355C9-989D-49FD-9BD1-D6ABFFC5B395.PNG",
  pepperSoup: "/PHOTO-2026-05-23-14-42-34.jpg",
  photo1: "/PHOTO-2026-05-23-14-35-14.jpg",
  photo2: "/PHOTO-2026-05-23-15-14-03.jpg",
  food3: "/Food3.jpg",
  food4: "/Food4.jpg",
  food5: "/Food5.jpg",
  food7: "/Food7.jpg",
  food12: "/Food12.jpg",
  food13: "/Food13.jpg",
  food14: "/Food14.jpg",
  food15: "/Food15.jpg",
  food16: "/Food16.jpg",
  suya: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2000&auto=format&fit=crop",
  grilledFish: "https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=2000&auto=format&fit=crop",
  riceDish: "https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=2000&auto=format&fit=crop",
  noodles: "/noodles-stirfry.jpg",
  salad: "https://images.unsplash.com/photo-1551248429-40975aa4de74?q=80&w=2000&auto=format&fit=crop",
  starter: "/vegetable-rolls.png",
  steak: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2000&auto=format&fit=crop",
  pasta: "/PHOTO-2026-05-23-15-30-40.jpg",
  dessert: "https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=2000&auto=format&fit=crop",
  wine: "https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?q=80&w=2000&auto=format&fit=crop",
  grill: "https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=2000&auto=format&fit=crop",
  interior1: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=2000&auto=format&fit=crop",
  interior2: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2000&auto=format&fit=crop",
  chef: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=2000&auto=format&fit=crop",
  lagos: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?q=80&w=2000&auto=format&fit=crop",
  market: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=2000&auto=format&fit=crop",
  ig: [
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=600&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=600&auto=format&fit=crop",
  ],
};

export const MENU = {
  Starters: [
    { name: "Vegetable Spring Roll (2pcs)", desc: "Two pieces. Crisp, golden, served with sweet chilli dip.", price: "₦4,500" },
    { name: "Chicken Spring Roll (2pcs)", desc: "Two pieces. Hand-rolled, lightly spiced, properly crisp.", price: "₦5,500" },
    { name: "Naan Bread (Cheese)", desc: "Soft, pulled, oozing. Straight from the tandoor.", price: "₦3,500" },
    { name: "Naan Bread (Garlic & Plain)", desc: "Brushed with garlic butter and fresh herbs.", price: "₦3,000" },
    { name: "Cream of Sweet Corn", desc: "Velvety, warming, finished with chive oil.", price: "₦4,000" },
    { name: "Tomato Cream Soup", desc: "Slow-roasted plum tomato, basil, a swirl of cream.", price: "₦4,000" },
    { name: "Cream of Mushroom Soup", desc: "Wild mushroom, thyme, truffle scent.", price: "₦4,500" },
    { name: "Chicken Corn Soup", desc: "Light, comforting. The kind your mother would approve of.", price: "₦4,500" },
    { name: "Gizzard in Plantain Sauce", desc: "Tender gizzard, ripe plantain, a Lagos signature.", price: "₦6,500" },
    { name: "Steam Veg/Potato + Protein Chops", desc: "Choice of chicken, fish or beef. Clean. Honest.", price: "₦7,500" },
  ],
  Salads: [
    { name: "Chicken Caesar Salad", desc: "Grilled chicken, romaine, parmesan, anchovy dressing.", price: "₦6,500" },
    { name: "Greek Salad", desc: "Tomato, cucumber, olive, feta, oregano, good oil.", price: "₦5,500" },
    { name: "Shrimps Cocktail Salad", desc: "Chilled shrimp, gem leaves, Marie Rose sauce.", price: "₦8,500" },
    { name: "Tuna Salad", desc: "Line-caught tuna, capers, red onion, lemon.", price: "₦6,500" },
    { name: "Potato Salad", desc: "Soft potatoes, boiled egg, mayo, mustard, dill.", price: "₦4,500" },
    { name: "Pasta Salad", desc: "Penne, peppers, sweetcorn, herb vinaigrette.", price: "₦5,000" },
    { name: "Mixed Vegetable Salad", desc: "Garden vegetables, house dressing.", price: "₦4,500" },
    { name: "Calamari Salad", desc: "Lightly fried calamari over crisp greens.", price: "₦7,500" },
    { name: "Mixed Avocado Salad", desc: "Avocado, mixed leaves, citrus, toasted seed.", price: "₦6,000" },
  ],
  Rice: [
    { name: "Jollof Rice", desc: "Smoky, party-style, the way Lagos taught us.", price: "₦5,500" },
    { name: "Fried Rice", desc: "Green pepper, carrot, liver, prawn, the proper way.", price: "₦5,500" },
    { name: "Ofada Rice/Sauce", desc: "Steamed ofada, ayamase sauce, assorted meat, boiled egg.", price: "₦7,500" },
    { name: "Chicken Stir Fried Rice", desc: "Wok-tossed with chicken, soy, garlic, scallion.", price: "₦6,500" },
    { name: "Beef Stir Fried Rice", desc: "Tender beef strips, wok-charred vegetables.", price: "₦7,500" },
    { name: "Seafood Stir Fried Rice", desc: "Prawn, calamari, fish. The catch in your rice.", price: "₦9,500" },
    { name: "Vegetarian Rice", desc: "Seasonal vegetables, herbed butter, simple, perfect.", price: "₦5,500" },
  ],
  Noodles: [
    { name: "Alfredo Noodles", desc: "Cream, parmesan, cracked pepper, parsley.", price: "₦6,500" },
    { name: "Chicken Stir Fry Noodles", desc: "Wok-tossed egg noodles, chicken, julienned veg.", price: "₦6,500" },
    { name: "Beef Stir Fry Noodles", desc: "Strips of beef, ginger, garlic, dark soy.", price: "₦7,500" },
    { name: "Seafood Stir Fry Noodles", desc: "Prawn and calamari, scallion, sesame.", price: "₦9,000" },
    { name: "Bolognese Noodles", desc: "Slow-cooked beef ragu, herbed tomato, parmesan.", price: "₦7,000" },
    { name: "Nigerian Vegetable Noodles", desc: "Indomie-meets-elevated. Pepper, scotch bonnet, crayfish.", price: "₦5,500" },
  ],
  "Pepper Soup & Specials": [
    { name: "Goat Meat Pepper Soup", desc: "Bone-in goat, uziza leaf, scotch bonnet. Pure fire and soul.", price: "₦7,500" },
    { name: "Assorted Meat Pepper Soup", desc: "Cow foot, tripe, shaki. For the brave.", price: "₦8,500" },
    { name: "Chicken Pepper Soup (All Goes with Bread)", desc: "Native chicken, full-flavoured broth, scent leaves.", price: "₦6,500" },
    { name: "Nkwobi", desc: "Cow foot in spicy palm-oil sauce, garden egg, utazi.", price: "₦8,500" },
    { name: "Isi Ewu", desc: "Goat head, slow-simmered, palm-oil sauce, the works.", price: "₦9,500" },
    { name: "Catfish Pepper Soup (Full)", desc: "Whole point-and-kill catfish, fiery broth.", price: "₦12,500" },
    { name: "Croaker Pepper Soup (Full)", desc: "Whole croaker, scent leaves, scotch bonnet.", price: "₦14,500" },
    { name: "Whole Chicken Native (Smoked)", desc: "Hours over wood, served whole, eat with your hands.", price: "₦16,500" },
    { name: "Chicken in Vegetable Sauce (Full)", desc: "Full chicken, smothered in spiced vegetable stew.", price: "₦15,000" },
  ],
  Continental: [
    { name: "Prawn Butterfly in Tartar Sauce", desc: "Butterflied prawn, panko crust, lemon tartar.", price: "₦11,500" },
    { name: "Prawn Butterfly with Potato Wedge or Parsley Potato", desc: "Your choice of side. Both excellent.", price: "₦12,500" },
    { name: "Battered Fish with Potato Wedge or Parsley Potato", desc: "Crisp batter, flaky fish, golden wedges or parsley potato.", price: "₦9,500" },
    { name: "Grilled Beef Steak Fillet in Black Pepper Sauce", desc: "Black pepper sauce, choice of rice or chips.", price: "₦14,500" },
    { name: "Grilled T-Bone Steak Fillet in Black Pepper Sauce", desc: "Black pepper sauce, choice of rice or chips. For meat people.", price: "₦18,500" },
    { name: "Fillet Fish and Chips with Tartar Sauce", desc: "Battered fillet, hand-cut chips, tartar.", price: "₦9,000" },
  ],
  Sauces: [
    { name: "Chicken in Mushroom Sauce (Hot Pot)", desc: "Marinated chicken, mushroom cream, served sizzling.", price: "₦9,500" },
    { name: "Beef Stroganoff in Hot Pot with Rice", desc: "Tender beef, sour cream, mushroom, paprika.", price: "₦11,500" },
    { name: "Beef Vegetable Sauce", desc: "Slow-cooked beef in spiced vegetable stew.", price: "₦8,500" },
    { name: "Chicken in Black Beans Sauce", desc: "Wok-finished, fermented black bean, ginger.", price: "₦8,500" },
    { name: "Beef in Black Beans Sauce", desc: "Tender strips, salty-sweet black bean glaze.", price: "₦9,500" },
    { name: "Chicken Curry Sauce", desc: "Coconut curry, fresh ginger, lime leaf.", price: "₦8,500" },
    { name: "Chicken in Vegetable Sauce", desc: "Garden vegetables, house pepper, soft chicken.", price: "₦8,000" },
    { name: "Heart in Black Beans Sauce", desc: "Beef heart, properly handled, properly seasoned.", price: "₦7,500" },
    { name: "Seafood Vegetable Sauce", desc: "Prawn, fish, calamari in a fragrant vegetable stew.", price: "₦11,000" },
  ],
  "Charcoal Grills": [
    { name: "Chicken Wings", desc: "Charred, glazed, finger-licking.", price: "₦6,500" },
    { name: "Buffalo Wings", desc: "Tossed in our house buffalo, blue cheese on the side.", price: "₦7,500" },
    { name: "Quarter Chicken", desc: "Spice-rubbed, over open charcoal.", price: "₦5,500" },
    { name: "Quarter Chicken with Chips", desc: "Same chicken, hand-cut chips.", price: "₦7,000" },
    { name: "Grilled Turkey with Chips", desc: "Smoked turkey, slow-grilled, chips on the side.", price: "₦9,500" },
    { name: "Fish: Catfish/Croaker/Tilapia", desc: "Whole fish, charred, scotch bonnet, lime.", price: "₦14,500" },
    { name: "Grilled Prawn", desc: "Head-on prawns, garlic butter, charred lemon.", price: "₦12,500" },
    { name: "Peppered Gizzard with Chips", desc: "Soft gizzard, pepper sauce, hand-cut chips.", price: "₦8,500" },
    { name: "Peppered Gizzard Alone", desc: "Just the gizzard. The way it should be.", price: "₦6,500" },
    { name: "Asun Only", desc: "Smoked goat, scotch bonnet, onion, lime.", price: "₦9,500" },
    { name: "Asun & Fries", desc: "Smoked goat, peppered, fries to soak it up.", price: "₦11,500" },
    { name: "Yam Fries", desc: "Hand-cut yam, golden, sea-salted.", price: "₦4,500" },
    { name: "Potato Fries", desc: "Hand-cut, double-cooked, properly salted.", price: "₦4,000" },
    { name: "Chicken (Native) Whole", desc: "Charcoal-grilled, served whole. Built to share.", price: "₦16,500" },
    { name: "Guinea Fowl (Whole)", desc: "Spice-rubbed, charcoal-grilled, lean and rich.", price: "₦18,500" },
  ],
  "National Dishes": [
    { name: "Assorted Beef", desc: "House stew, oxtail, tripe, shaki. A proper plate.", price: "₦8,500" },
    { name: "Goat", desc: "Slow-braised in our signature stew.", price: "₦9,500" },
    { name: "Cow Tail", desc: "Soft, falling-off-the-bone oxtail.", price: "₦9,500" },
    { name: "Native Chicken", desc: "Free-range, deeper flavour, served in stew.", price: "₦8,500" },
    { name: "Fish (Croaker/Tilapia)", desc: "Whole fish, stewed or grilled. Your choice.", price: "₦12,500" },
    { name: "Turkey", desc: "Smoked or stewed. Both quietly excellent.", price: "₦8,500" },
    { name: "Dry Fish", desc: "Sun-dried fish, soft in the stew, deep umami.", price: "₦7,500" },
    { name: "Stock Fish", desc: "Properly soaked, properly cooked. Deep umami, richly satisfying.", price: "₦8,500" },
    { name: "Snail", desc: "Cleaned, peppered, slow-cooked. A delicacy.", price: "₦10,500" },
    { name: "Guinea Fowl", desc: "Lean, gamey, served in our house stew.", price: "₦11,500" },
  ],
  "Traditional Specials": [
    { name: "Seafood Okro", desc: "Fresh okro, prawn, fish, periwinkle. Coastal in a bowl.", price: "₦9,500" },
    { name: "Banga", desc: "Palm-fruit extract, beletientien, fish. Warmly aromatic.", price: "₦8,500" },
    { name: "Pocho", desc: "Bitter leaf, scent leaf, assorted meat. Rich and deeply flavoured.", price: "₦8,500" },
    { name: "Ikokore/Eberipo", desc: "Pounded water yam, slowly stewed in pepper.", price: "₦8,000" },
    { name: "Miyan & Kuka", desc: "Baobab leaf soup, deep and earthy.", price: "₦7,500" },
    { name: "Fisherman Soup", desc: "Catfish, prawn, periwinkle, crab. The catch of the day.", price: "₦11,500" },
    { name: "Ofensala/White Soup", desc: "Pepper soup spiced, no palm-oil, deeply satisfying.", price: "₦8,500" },
  ],
};
